[server]
listenAddr="localhost"
port="8000"
readTimeout=5
writeTimeout=5
closeTimeout=5
env="dev"
useMemoryStore=true

[api]
mode="dev"
enableTestRoute=true 
enableMediaRoute=true
enableStaticRoute=true

[token]
jwtSignKey="cn2eiudh"

[kafka]
brokerDial="tcp"
brokerUrl="localhost"
brokerPort="29092"

[logger]
enableKafkaLog=false
enableConsoleLog=true
kafkaTopic="log"
kafkaParition=1

[database]
scheme="mongodb"
username=""
password=""
host="localhost:27017"
replicaSet=""

[redis]
network="tcp"
host="localhost"
port="6379"
password=""
username=""

[middleware]
enableRequestLog=true
